### ISSUE TITLE
[Support]: PostgreSQL - do not store clear password for SMTP auth

### ISSUE THREAD

**Issue by tinola** [sinamics/ztnet#154]
### 📝 Describe the Problem You Are Having

Hi,

I found possible security risk!
In `GlobalOptions` table there is `smtpPassword` column, where the password for SMTP auth is stored as clear text!
This value should be encrypted...

### 🔖 Version

main

### 💻 Operating System

Other

**Comment by imyller** [comment]
@sinamics Maybe replace `NEXTAUTH_SECRET` with more generic `ZTNET_AUTH_SECRET` (or similar) and use that salted with some predetermined context suffix (`_nextauth`, `_smtp`) as instance specific auth secret.

Then encrypt/decrypt any stored passwords (such as smtp) with aes-256 using this secret as a passphrase.

With passphrase context salting potential leak in Nextauth stack would not compromise database. Similarly leak in database would not compromise Nextauth.

In addition, you could use this same secret base if future development requires storing passwords or auth tokens.

**Comment by imyller** [comment]
For generating correct length and secure AES keys from custom random length user provided passphrases I personally prefer to use PBKDF2, which is CPU heavy. Another good alternatives are memory intensive scrypt or argon2. However the choice also depends on the use case. 

Some applications prefer CPU heavy algorithms and some memory heavy algorithms based on the runtime environment and the expected load caused by hashing operations.

These hashing functions can be found in standard Node.js crypto-library:

https://nodejs.org/api/crypto.html#cryptopbkdf2password-salt-iterations-keylen-digest-callback

https://nodejs.org/api/crypto.html#cryptoscryptpassword-salt-keylen-options-callback

Argon2 is not available in Node.js standard library, but is available as module.

PBKDF2 is only secure with enough difficulty or iterations is configured for the algorithm. Current recommendation is at least 600 000 iterations. Scrypt and more modern argon2 also require enough computational/memory resource difficulty to be secure.

Some quotes about current recommended difficulty levels:

>If FIPS-140 compliance is required, use PBKDF2 with a work factor of 600,000 or more and set with an internal hash function of HMAC-SHA-256

> Use scrypt with a minimum CPU/memory cost parameter of (2^17), a minimum block size of 8 (1024 bytes), and a parallelization parameter of 1


> Use Argon2 with a minimum configuration of 19 MiB of memory, an iteration count of 2, and 1 degree of parallelism.

**Comment by sinamics** [comment]
@tinola Thx for reporting, i know it was just a matter of time before this issue was posted. I had this item on my todo list. 
Thank you @imyller for exellent suggestion on making a generic env secret and salt it with instance specific strings.
