### ISSUE TITLE
[Feature Request]: Disabling login

### ISSUE THREAD

**Issue by PovilasID** [sinamics/ztnet#187]
### 🚀 Feature Summary

Having an environmental variable that disables authentication

### 📝 Detailed Description

Since there is a lack of Oauth support #168 it can be implemented externally by reverse proxies in cases where multi users functionality is not necessary.
I am looking for a docker environmental variable that turns off login page and logs in as designated user `LOGIN_BYPASS_USER=admin` or just default admin `LOGIN_BYPASS=true`

### 🎯 Use Case

I am using local controllers where in situation where it is going to be only one ZeroTier network and one user managing said network, so I do not really need for there to be multiple users. 
I also have revers proxy (traefik) with authentication forwarding handed off (Keycloak) handling other apps that do not have authentication already set up, so I can have external permission management keeping logins the same over all aplications.  

### 💡 Willing to Contribute

None

**Comment by sinamics** [comment]
Hi
Im also using traefik as the reverse proxy, but im using authelia for the authenication part. 
As both authelia and ztnet has long lived refresh tokens, i rarly need to login to either of the application. I know this is user defined prefrences. 

For ztnet, you can also turn of the user registration if you dont want the multi user functionallities. 

However, should we implement such feature, i would rather add this option in the application itself. 
Using environment variables might be a valid solution, I believe a more flexible and controlled approach would be to integrate this feature directly into the application.

### Proposed Workflow:
1. A user must initially register and be assigned the role of 'Admin'.
2. After successful authentication, this Admin user would then have the capability within the application UI to disable the authentication process if no other user has registered.
3. When the authentication is disabled, the application would automatically log user in as the designated Admin, eliminating the need for credentials.

At this time, this feature will not be prioritized on my end due to other parts that needs my attention.
if someone wants to try implementing it, I'll be glad to review the Pull Request.

**Comment by PovilasID** [comment]
Proposed workflow would work for me too.

>  i rarly need to login

I would not be the one using it. A non technical person would, so 'rarely' would mean I would get a call every time asking me "Why my password is not working?", so for now I will stick to other ZT network UI that lets you do this (though your UI is nicers and has some really nice other features :) )

**Comment by sinamics** [comment]
After giving it some thought, I've decided not to implement the authentication bypass feature in ztnet.
Ztnet is designed with organization and multiuser support, and removing the login process would essentially disable this functionality completly.

Also, Ztnet just got OAuth support. Implementing a bypass feature would significantly increase the maintenance workload and add complexity to the platform.
