### ISSUE TITLE
[Support]: Successfully deployed the software and found the following issues during use，Thank you for your help

### ISSUE THREAD

**Issue by surfboy2000** [sinamics/ztnet#47]
### Describe the problem you are having

1.can i  delete the members in deleted members group forever?but , i find no way to do it .

2.the address of members is randomly assigned, can i custom setting the member's address ?

3.windows(win10) client  join the network first successfully,but  it  joined next time, the status of zerotier-cli listnetworks is REQUESTING_CONFIGURATION, what is wrong?

### Version

docker image tag 

### Operating system

Windows

**Comment by sinamics** [comment]
Hi
1) This functionalities does not exist currently, but its on top of my todo list. 
2) In ZeroTier, each node has a unique address that is generated from its cryptographic identity. This address acts as an identifier for the node on the network. It is not possible to manually change it as far as i know, but if you find a way let me know.
3) Im not sure i understand the question. Are the windows pc stuck at "REQUESTING_CONFIGURATION" ? 
make sure you have opened port 9993/udp towards the zerotier application in your firewall.

**Comment by sinamics** [comment]
I've added the delete user functionality to the application. Now, you can completely remove (force delete) a user from the network_members table after stashing them.  The reason why i keep the stash / zombie table is due to the fact that users is not instantly deleted from the controller and stash them will prepear the user to be deleted. 

Feel free to try version `v0.0.23`
